//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planet.Domain.Resources.OperationResources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationMessages() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Planet.Domain.Resources.OperationResources.OperationMessages", typeof(OperationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Listeye eleman başarılı bir şekilde eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddedCardCheckListItemSuccessfully {
            get {
                return ResourceManager.GetString("AddedCardCheckListItemSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kontrol listesi başarılı bir şekilde eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddedCheckListToCardSuccessfully {
            get {
                return ResourceManager.GetString("AddedCheckListToCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart yorumu başarılı bir şekilde eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddedCommentToCardSuccessfully {
            get {
                return ResourceManager.GetString("AddedCommentToCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etiket başarılı bir şekilde oluşturuldu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddedLabelSuccessfully {
            get {
                return ResourceManager.GetString("AddedLabelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etiket karta başarılı bir şekilde eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddedLabelToCardSuccessfully {
            get {
                return ResourceManager.GetString("AddedLabelToCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liste başarılı bir şekilde oluşturuldu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddedListSuccessfully {
            get {
                return ResourceManager.GetString("AddedListSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano davet bağlantısı oluşturuldu. Bağlantıyı paylaşarak panonuza üyeleri davet edebilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoardInvitationUrlCreatedSuccessfully {
            get {
                return ResourceManager.GetString("BoardInvitationUrlCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atanmak istenen etiket bulunamadı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoardLabelNotFound {
            get {
                return ResourceManager.GetString("BoardLabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano listesi başarıyla düzenlendi.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoardListEditedSuccesfully {
            get {
                return ResourceManager.GetString("BoardListEditedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano listesi bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoardListNotFound {
            get {
                return ResourceManager.GetString("BoardListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoardNotFound {
            get {
                return ResourceManager.GetString("BoardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Herhangi bir karta sahip bir pano listesi silinemez. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CanNotRemoveBoardListThatContainsCard {
            get {
                return ResourceManager.GetString("CanNotRemoveBoardListThatContainsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano sahibi üyelikten çıkarılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CanNotRemoveBoardOwner {
            get {
                return ResourceManager.GetString("CanNotRemoveBoardOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart bulunamadı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kontrol listesi bulunamadı.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CheckListNotFound {
            get {
                return ResourceManager.GetString("CheckListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano başarılı bir şekilde oluşturuldu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreatedBoardSuccessfully {
            get {
                return ResourceManager.GetString("CreatedBoardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart başarılı bir şekilde oluşturuldu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreatedCardSuccessfully {
            get {
                return ResourceManager.GetString("CreatedCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano kartlarına kontrol listesi eklemek için yetkiniz bulunmamaktadır.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForAddCardCheckList {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForAddCardCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano kartlarına kullanıcı atamak için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForAssigningUserToCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForAssigningUserToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano için üye davet yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForBoardInviting {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForBoardInviting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano için kart oluşturma yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForCreatingCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForCreatingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kontrol listesi başlığını düzenlemek için yetkiniz bulunmamaktadır.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForEditCardCheckListTitle {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditCardCheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano kartlarının yorumlarını düzenlemek için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForEditCardComment {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditCardComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano kartlarının açıklamasını düzenlemek için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForEditCardDescription {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano için bu kartın tarihini düzenleme yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForEditDateCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditDateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano özelliklerini değiştirmek için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForEditingBoard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kartı düzenleme yetkiniz bulunmamaktadır! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForEditingCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano listelerini düzenlemek için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForManagingBoardLists {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForManagingBoardLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano üyelerini yönetmek için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForManagingBoardMembers {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForManagingBoardMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart taşıma işlemi için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForMovingCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForMovingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart kontrol listesini kaldırmak için yetkiniz bulunmamaktadır.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForRemoveCardCheckList {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForRemoveCardCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panoyu görüntülemek için yetkiniz bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoNotHavePermissionForViewingBoard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForViewingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano özellikleri başarılı bir şekilde değiştirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditedBoardSuccessfully {
            get {
                return ResourceManager.GetString("EditedBoardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liste elemanı başarılı bir şekilde güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditedCardCheckListItemSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardCheckListItemSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart günleri başarılı bir şekilde güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditedCardDateSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardDateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart açıklaması başarılı bir şekilde değiştirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditedCardDescriptionSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardDescriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart başlığı başarılı bir şekilde değiştirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditedCardTitleSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardTitleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kontrol listesi başlığı başarılı bir şekilde değiştirildi.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditedCheckListTitleSuccessfully {
            get {
                return ResourceManager.GetString("EditedCheckListTitleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belirtilen e-posta adresi daha önce kullanılmış. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belirtilen e-posta adresine kayıtlı bir kullanıcı bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Davet bağlantısı artık geçerli değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExpiredInvitationKey {
            get {
                return ResourceManager.GetString("ExpiredInvitationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panoya başarılı bir şekilde katıldınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string JoinedBoardSuccessfully {
            get {
                return ResourceManager.GetString("JoinedBoardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart başarılı bir şekilde taşındı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MovedCardSuccessfully {
            get {
                return ResourceManager.GetString("MovedCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parolanız başarılı bir şekilde değiştirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum yenileme işleminin süresi doldu. Lütfen tekrar giriş yapınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum yenileme anahtarı geçerli değil. Lütfen tekrar giriş yapınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("RefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano listesi başarılı bir şekilde kaldırıldı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RemovedBoardListSuccessfully {
            get {
                return ResourceManager.GetString("RemovedBoardListSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pano üyesi başarılı bir şekilde panodan kaldırıldı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RemovedBoardMemberSuccessfully {
            get {
                return ResourceManager.GetString("RemovedBoardMemberSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liste elemanı başarılı bir şekilde kaldırıldı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RemovedCardCheckListItemSuccessfully {
            get {
                return ResourceManager.GetString("RemovedCardCheckListItemSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart kontrol listesi başarılı bir şekilde kaldırıldı.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RemovedCheckListFromCardSuccessfully {
            get {
                return ResourceManager.GetString("RemovedCheckListFromCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde giriş yaptınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SignedInSuccessfully {
            get {
                return ResourceManager.GetString("SignedInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturumunuz başarılı bir şekilde yenilendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SignedInWithRefreshTokenSuccessfully {
            get {
                return ResourceManager.GetString("SignedInWithRefreshTokenSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı kaydınız başarılı bir şekilde yapıldı. Belirlediğiniz e-posta adresi ve şifreniz ile giriş yapabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SignedUpSuccessfully {
            get {
                return ResourceManager.GetString("SignedUpSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yanlış kullanıcı adı veya şifre! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eski şifre yanlış. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
